# Generated by Django 4.2.7 on 2024-02-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_featuredproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredproducts',
            name='group',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
