# Generated by Django 4.2.7 on 2024-03-09 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_bestselling_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BestSelling',
        ),
    ]
