# Generated by Django 4.2.7 on 2024-02-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(default='category.jpg', upload_to='category'),
        ),
    ]
