# Generated by Django 4.2.7 on 2024-03-10 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_products_date_products_featured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='returns_product',
        ),
        migrations.RemoveField(
            model_name='products',
            name='shipping',
        ),
    ]
